// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RoomExpenseTracker.Data;

namespace RoomExpenseTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("RoomExpenseTracker.Models.User", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("RoomExpenseTracker.Models.Expense", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("UserName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<decimal>("Amount").HasColumnType("decimal(12,2)");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("ExpenseDate").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Expenses");
            });

            modelBuilder.Entity("RoomExpenseTracker.Models.Absence", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("FromDate").HasColumnType("datetime2");
                b.Property<DateTime>("ToDate").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Absences");
            });
        }
    }
}
